//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.lZiMUl.BiliBili_Anchor_Assistant.Resources.Languages {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.lZiMUl.BiliBili_Anchor_Assistant.Resources.Languages.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 活动.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 添加歌曲.
        /// </summary>
        internal static string add_song {
            get {
                return ResourceManager.GetString("add_song", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 作家.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 断开连接.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已断开.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 英文.
        /// </summary>
        internal static string en_us {
            get {
                return ResourceManager.GetString("en_us", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即重启.
        /// </summary>
        internal static string immediate_restart {
            get {
                return ResourceManager.GetString("immediate_restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 稍后重启.
        /// </summary>
        internal static string later_restart {
            get {
                return ResourceManager.GetString("later_restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        internal static string menus {
            get {
                return ResourceManager.GetString("menus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 房间 Id: .
        /// </summary>
        internal static string room_id {
            get {
                return ResourceManager.GetString("room_id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 歌曲管理器.
        /// </summary>
        internal static string song_manager {
            get {
                return ResourceManager.GetString("song_manager", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待中.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 由于您更改了客户端语言, 需要重启客户端才能生效, 是否现在重启?.
        /// </summary>
        internal static string warning_content {
            get {
                return ResourceManager.GetString("warning_content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string zh_cn {
            get {
                return ResourceManager.GetString("zh_cn", resourceCulture);
            }
        }
    }
}
